# ------------------------------------------------------------------------------
#  Copyright (c) 2023-2024 Your Name
#  Distributed under the license of your choice
# ------------------------------------------------------------------------------

name: CMake Build & Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        compiler:
          - {name: gcc, version: 11, c_compiler: gcc-11, cpp_compiler: g++-11}
          - {name: gcc, version: 12, c_compiler: gcc-12, cpp_compiler: g++-12}
          - {name: gcc, version: "", c_compiler: gcc, cpp_compiler: g++}  # Latest version
          - {name: clang, version: "", c_compiler: clang, cpp_compiler: clang++}  # Latest version
        standard: [20]
        include:
          # MSVC for Windows
          - os: windows-latest
            compiler: {name: msvc, version: "", c_compiler: cl, cpp_compiler: cl}
            build_type: Release
            standard: 20
        exclude:
          # Remove combinations that don't make sense
          - os: windows-latest
            compiler: {name: gcc, version: 11, c_compiler: gcc-11, cpp_compiler: g++-11}
          - os: windows-latest
            compiler: {name: gcc, version: 12, c_compiler: gcc-12, cpp_compiler: g++-12}
          - os: windows-latest
            compiler: {name: gcc, version: "", c_compiler: gcc, cpp_compiler: g++}
          - os: windows-latest
            compiler: {name: clang, version: "", c_compiler: clang, cpp_compiler: clang++}
          # MacOS typically uses Clang but we still allow specific versions
          - os: macos-latest
            compiler: {name: gcc, version: 11, c_compiler: gcc-11, cpp_compiler: g++-11}
          - os: macos-latest
            compiler: {name: gcc, version: 12, c_compiler: gcc-12, cpp_compiler: g++-12}
          - os: macos-latest
            compiler: {name: gcc, version: "", c_compiler: gcc, cpp_compiler: g++}

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up build environment (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Install GCC
        if: matrix.compiler.name == 'gcc' && runner.os == 'Linux'
        run: |
          if [ "${{ matrix.compiler.version }}" != "" ]; then
            sudo apt-get install -y gcc-${{ matrix.compiler.version }} g++-${{ matrix.compiler.version }}
            echo "CC=gcc-${{ matrix.compiler.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.compiler.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y gcc g++
            echo "CC=gcc" >> $GITHUB_ENV
            echo "CXX=g++" >> $GITHUB_ENV
          fi

      - name: Install Clang
        if: matrix.compiler.name == 'clang' && runner.os == 'Linux'
        run: |
          if [ "${{ matrix.compiler.version }}" != "" ]; then
            sudo apt-get install -y clang-${{ matrix.compiler.version }}
            echo "CC=clang-${{ matrix.compiler.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.compiler.version }}" >> $GITHUB_ENV
          else
            sudo apt-get install -y clang
            echo "CC=clang" >> $GITHUB_ENV
            echo "CXX=clang++" >> $GITHUB_ENV
          fi

      - name: Install specific Clang on macOS
        if: matrix.compiler.name == 'clang' && runner.os == 'macOS' && matrix.compiler.version != ''
        run: |
          brew install llvm@${{ matrix.compiler.version }}
          echo "CC=/usr/local/opt/llvm@${{ matrix.compiler.version }}/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/local/opt/llvm@${{ matrix.compiler.version }}/bin/clang++" >> $GITHUB_ENV
          
      - name: Use default Clang on macOS
        if: matrix.compiler.name == 'clang' && runner.os == 'macOS' && matrix.compiler.version == ''
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          
      - name: Set up Windows environment variables
        if: runner.os == 'Windows'
        run: |
          echo "CC=${{ matrix.compiler.c_compiler }}" >> $env:GITHUB_ENV
          echo "CXX=${{ matrix.compiler.cpp_compiler }}" >> $env:GITHUB_ENV
      
      - name: Set up build environment (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja
          
      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build 
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.compiler.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config ${{ matrix.build_type }} --output-on-failure --verbose

  sanitizers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
        
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Configure with ${{ matrix.sanitizer }} sanitizer
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer"
          -DCMAKE_C_FLAGS="-fsanitize=${{ matrix.sanitizer }} -fno-omit-frame-pointer"
          -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=${{ matrix.sanitizer }}"
          -S ${{ github.workspace }}
          
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Debug
        
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config Debug --output-on-failure --verbose
        
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy
          
      - name: Configure with clang-tidy
        run: >
          cmake -B ${{ github.workspace }}/build
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_CXX_STANDARD=17
          -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=*,-fuchsia-*,-google-*,-llvm-header-guard,-cppcoreguidelines-owning-memory,-hicpp-no-array-decay,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-modernize-use-trailing-return-type,-readability-identifier-length"
          -DENABLE_SOFTFLOAT_BENCHMARK=OFF
          -S ${{ github.workspace }}
          
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Debug
        
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest --build-config Debug --output-on-failure --verbose
